### ISSUE TITLE
ClientException: page limit reached, please use scroll API

### ISSUE THREAD

**Issue by Cimballi** [intercom/intercom-java#117] opened 2016-08-26 16:51 UTC
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-java version: 2.1.0
  - Java version: 1.8.x

## Expected behavior
I got the exception while retrieving all the users for a segment.

## Actual behavior
Exception in thread "main" io.intercom.api.ClientException: page limit reached, please use scroll API

## Steps to reproduce
The segment had 10620 users at that time.

## Logs
Exception in thread "main" io.intercom.api.ClientException: page limit reached, please use scroll API
        at io.intercom.api.HttpClient.throwException(HttpClient.java:205)
        at io.intercom.api.HttpClient.handleError(HttpClient.java:164)
        at io.intercom.api.HttpClient.runRequest(HttpClient.java:150)
        at io.intercom.api.HttpClient.executeHttpMethod(HttpClient.java:105)
        at io.intercom.api.HttpClient.get(HttpClient.java:81)
        at io.intercom.api.HttpClient.get(HttpClient.java:77)
        at io.intercom.api.TypedDataCollection.fetchNextPage(TypedDataCollection.java:44)
        at io.intercom.api.UserCollection.nextPage(UserCollection.java:33)
        at io.intercom.api.UserCollection.nextPage(UserCollection.java:9)
        at io.intercom.api.TypedDataCollectionIterator.hasNext(TypedDataCollectionIterator.java:19)
        at io.intercom.api.UserCollection.hasNext(UserCollection.java:37)

**Comment by mariokostelac** [comment] 2016-08-31 14:24
This one is dupe of https://github.com/intercom/intercom-java/issues/118.
Once the client implements scroll API, you will be able to see all users.

**Closed by mariokostelac** 2016-08-31 14:24 UTC
