### ISSUE TITLE
API deprecation

### ISSUE THREAD

**Issue by rogierslag** [intercom/intercom-java#131] opened 2016-11-15 12:41 UTC
## Version info
  - intercom-java version: 2.0.0
  - Java version: 1.8u102

## Expected behavior

Currently there is no indication which versions of this plugin are still supported by the actual API. We were on 2.0.0, when we noticed that since a few days, the bulk updating of users started to fail. Upgrading to 2.2.2 fixed the issue.

In this case a call to `User.submit` return null instead of a `Job` object

Please publish a list of versions and dates until these are supported as part of the readme.

## Actual behavior

No information about supported versions is available

**Comment by rogierslag** [comment] 2017-01-16 15:27
Is there any response to this?

**Comment by choran** [comment] 2017-08-24 13:24
Hi @rogierslag 
Apologies fro the late response. We were reviewing some old issues and I see this was never responded to.
All versions of the plugin should be supported by the API. What I mean is that we try, where possible, not to make breaking changes to the SDK. When we do change something in the SDK it is generally to add some feature to the SDK that either 1/ existed in the API but was not in one or all sdks, e.g. you can list user events in the API but some SDKs might not support that. Or 2/ We add some feature to the SDK that was newly added to the API, e.g. we added scroll feature to the API and then gradually added it to the SDKs. So all the version should work with the API but some will have added features and these features should then be updated in the README.
Does that make sense or is that different to what you were asking?
In relation to your issue with bulk jobs, I think it was [this change](https://github.com/intercom/intercom-java/pull/129) which may have added the new datatype. Does the commit looks like the change that you were referring to?

**Comment by choran** [comment] 2017-10-13 13:25
Hi @rogierslag 
I am not sure if this is still an issue you are experiencing?
I will close this for now but feel free to reopen if you are still experiencing an issue.
If you do have an issue any example code relating to that issue would be helpful in trying to reproduce this issue.
Thanks
Cathal

**Closed by choran** 2017-10-13 13:25 UTC
Labels: question
