### ISSUE TITLE
Admin Initiated Conversation throwing Null Pointer Exception

### ISSUE THREAD

**Issue by itchap** [intercom/intercom-java#145] opened 2017-06-13 12:48 UTC
## Version info
  - intercom-java version: 2.2.5
  - Java version: 1.8.0_12

## Expected behavior
Admin Initiated InApp message to be sent to a user via the REST API.

## Actual behavior
Conversation.create method is throwing a Null Pointer Exception

## Steps to reproduce

Code used:
```

package itchap.intercom.api;

import io.intercom.api.Admin;
import io.intercom.api.AdminMessage;
import io.intercom.api.Conversation;
import io.intercom.api.Intercom;
import io.intercom.api.User;

public final class NewAdminConversation {
   public static void main(String[] args)\{
		
      String TOKEN = "<token here>";
      Intercom.setToken(TOKEN);
        
      Admin sender = new Admin().setId("886729");
      User recipient = new User().setId("5939fb030a13a09bbb1ccb71");
      String message="This is a test Admin initiated InApp message.";
      
      AdminMessage adminMessage = new AdminMessage()
            .setAdmin(sender)
            .setUser(recipient)
            .setBody(message)
            .setMessageType("inapp");
        
      Conversation.create(adminMessage);
        
      System.out.println("\nYour message has been sent successfully.");
   }
}
```

## Logs
```
Exception in thread "main" java.lang.NullPointerException
	at io.intercom.api.Conversation.create(Conversation.java:83)
	at itchap.intercom.api.NewAdminConversation.main(NewAdminConversation.java:25)
```

**Comment by itchap** [comment] 2017-06-14 13:35
I figured out what is wrong :)

The Conversation.create method is expecting all values to be filled for inapp message including email type settings like .setSubject and .setTemplate.

Our [Dev Docs](https://developers.intercom.com/reference#admin-initiated-conversation) state that these parameters are not required if you are only sending an inApp message but it seems that is not managed correctly by the Java SDK. 

Hope that helps!
Pete

**Comment by choran** [comment] 2017-08-24 13:41
Sorry @itchap meant to get back to this sooner.
I did think we allowed for these field not to be set, you can see [here](https://github.com/intercom/intercom-java/blob/6b9da2c652028228e3cdda15a7c024927b836d56/intercom-java/src/main/java/io/intercom/api/AdminMessage.java#L25) that we set a default to make sure the inapp can be used without needing values to be set here. 
But it sounds like this may not be working as expected so let me look into it a little more and get back to you

**Comment by choran** [comment] 2017-10-12 14:23
Hi @itchap 
I was able to get this working correctly with your code above.
So you do not need to add the subject or template fields for and 'inapp' message
I am guessing it was another issue, but it is strange that it looks like it was resolved by adding the extra fields.

I will close this for now, but if you can reproduce the failing issue and you still cannot send msgs without adding the extra fields for an inapp message please re-open and I will investigate further

Here is the code I used for context (I copied yours from above to use same layout)
```
        Admin sender = new Admin().setId("824851");
        User recipient = new User().setId("599d6bbeada470883ed8ba7c2");
        String message="This is a test Admin initiated InApp message.";

        AdminMessage adminMessage = new AdminMessage()
                .setAdmin(sender)
                .setUser(recipient)
                .setBody(message)
                .setMessageType("inapp");
        Conversation.create(adminMessage);
        System.out.println("\nYour message has been sent successfully.");
```

**Closed by choran** 2017-10-12 14:23 UTC
Labels: bug
