### ISSUE TITLE
Size of library. 

### ISSUE THREAD

**Issue by levibostian** [intercom/intercom-java#134] opened 2016-12-03 03:34 UTC
## Version info
  - intercom-java version: 3.0.9

I am going through an Android app I am working on currently and trying to speed up the compile time on it. I am going through each of my dependencies and removing ones that have a high method count. 

I noticed that Intercom Java is a pretty big size library. In fact, I used [this tool](https://inloop.github.io/apk-method-count/) to analyze my APK and Intercom comes in 2nd place for biggest dependency behind Android and the support libraries I am using. 

<img width="266" alt="screen shot 2016-12-02 at 9 32 14 pm" src="https://cloud.githubusercontent.com/assets/2041082/20856554/3b2da0d8-b8d7-11e6-8426-46f0e9bfee2a.png">

Is there any way I can skim down Intercom Java? Thank you!

**Comment by harkin** [comment] 2016-12-05 11:29
Hi @levibostian,

This library wasn't designed for use in Android apps and, more importantly, shouldn't be used in them. 

The main reason not to use it is security concerns: the naive integration involves shipping your personal access token in the apk that gets installed on every phone. It's trivial to retrieve this from the installed apk and once someone has your personal access token they have the key to access most/all of your data in Intercom and the ability to write whatever they want too. Normally we recommend having an intermediary service on a server you control that knows your PAT and can communicate with Intercom, having your app talk to that server with some verifications that requests are coming from your app, and only exposing the subset of functionality you need to your app (eg user updates and conversation replying instead of **everything**).

Another alternative is to use https://github.com/intercom/intercom-android which is our Messenger designed for Android. It doesn't have the same breadth of API abilities in there, instead it's focused on the life of a single user in your app with the ability to update that user and log events for them. Security is also a concern here but we've been deliberate about how api keys are scoped for the mobile Messengers and we've also built in a request signing process that we call 'secure mode' to verify that traffic to Intercom is coming from your app. 

To go into a little detail about why this library is large the first place to look is it's own dependencies: Guava, Jackson and an Apache Commons codec are the three largest at 14k, ~2k and ~1k methods respectively. Guava is full of useful niceties and when we aren't constraining ourselves with a method count limit it's handy to have. I'm not familiar with how deep we've gone on it but I doubt we'd want to drop it as a dependency without a compelling reason. Jackson is a similar story, it's the JSON parsing library of choice here mostly because of familiarity to the writers and maintainers. Off the top of my head I don't know if Gson is substantially smaller and it's doubtful we'd switch to something like Moshi here. The Commons dependency is used for very few things and could be removed quite easily I think. Removing it is not a priority for us at all; PRs are always welcome :)

It looks like you're already using Proguard in your project (`io.a` is a giveaway) so i don't think there's much else you can do to make the library smaller. There are some optimisations you could make like also using Jackson if you need to do JSON parsing in your app so that they can share a dependency but that's about all. 

I'm really curious why you are using the Java library in your project instead of the Android one. We've found that generally the limited API we expose in the Android library is enough for what people need to do; if that isn't true we'd love to know so we can expand it.

**Comment by levibostian** [comment] 2016-12-05 18:12
@harkin, I am super sorry, but I am indeed using Intercom Android in my app. Simple mistake on my part. 

Proguard does it's duty, but I am trying to slim my app down to cut down on compile time. 

I really wish Commons was broken into multiple dependencies. In a previous project I worked on, I found out I was only using 4 functions in the whole library and just pulled those functions out of the source code. 

Those libraries are useful to have in the library, I understand that. It seems like a pretty heavy library where I only use it for the messenger.

**Comment by harkin** [comment] 2016-12-06 10:39
@levibostian ah, you can safely disregard everything I said above then. I was talking specifically about this repo which is our general purpose Java bindings for the Intercom API.

The Android Messenger is large for different reasons. We've been a lot more deliberate about what dependencies we have there and so **don't** use ones like Guava or Commons. You can see the dependency list [here](https://github.com/intercom/intercom-android#intercom-sdk-base. Briefly, it's the Square networking stack, Glide for images, and Gson for JSON parsing. If you use the same dependencies in your app it might be useful to check out [this guide](https://docs.intercom.com/using-transitive-dependencies-with-intercom-for-android-8716-ddc96f) on how to use them transitively in your app. 

I'm going to close this here as the issue isn't with this repo, if you want to continue the conversation could you open an issue [here](https://github.com/intercom/intercom-android/issues} or just write in to us in Intercom; we're more than happy to help where we can 😸

**Closed by harkin** 2016-12-06 10:39 UTC

**Comment by levibostian** [comment] 2016-12-06 18:11
@harkin thank you for the time. Again, sorry about my mistake. You were very helpful.
