### ISSUE TITLE
Exception in thread "main" io.intercom.api.ServerException: service error

### ISSUE THREAD

**Issue by Cimballi** [intercom/intercom-java#119] opened 2016-08-30 20:48 UTC
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io
## Version info
- intercom-java version: 2.1.0
- Java version: 1.8.x
## Expected behavior

API should work.
## Actual behavior

From time to time, we get the exception:
Exception in thread "main" io.intercom.api.ServerException: service error

What are the reasons for such an error ? What do you advice to do in such a case ?
## Steps to reproduce
1. 
2. 
3. 
## Logs

Exception in thread "main" io.intercom.api.ServerException: service error
        at io.intercom.api.HttpClient.throwException(HttpClient.java:207)
        at io.intercom.api.HttpClient.handleError(HttpClient.java:164)
        at io.intercom.api.HttpClient.runRequest(HttpClient.java:150)
        at io.intercom.api.HttpClient.executeHttpMethod(HttpClient.java:105)
        at io.intercom.api.HttpClient.post(HttpClient.java:95)
        at io.intercom.api.DataResource.create(DataResource.java:27)
        at io.intercom.api.Job.submit(Job.java:49)
        at io.intercom.api.Event.submit(Event.java:45)
        at io.intercom.api.Event.submit(Event.java:40)

**Comment by choran** [comment] 2017-08-24 11:11
Hi @Cimballi 
We are just reviewing some older issues here. Unfortunately, I was not able to reproduce this, I was unsure what you were trying to do at the time. I was not sure if this was still an issue you were experiencing?
For now I will close this issue. However, if you are still experiencing this please re-open it and let us know along with a request ID or some example of the operation that you were performing at the time. That would help us understand the issue.
Thanks
Cathal

**Closed by choran** 2017-08-24 11:11 UTC
Labels: question
